### ISSUE TITLE
db.put function duplicates information

### ISSUE THREAD

**Issue by sksar** [mafintosh/flat-file-db#7]
when i run 
`db.put('hello', {world:1});`
and then at a later time after closing and reopening i run that again 

i get two entries of `hello`?? why is this so?? from the api i am never gonna get the previous value of `hello` so why does the value still persists.. is there a way not to make such things happen so that the file size gets reduced

**Comment by matthew-dean** [comment]
Wait, does this really happen?

**Comment by mafintosh** [comment]
When you override 'hello' the old version is marked as garbage in the file. It will be overwritten by another put in the future. This means that you'll usually only ever have two versions of 'hello' in the version.
